# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ba68c7f426a3ae84d62a7ce62defab72db10d3ca644a412404e89935757886f1e480dbac785cd26d63cd1f1a3e6760a53d5a4233e36afeca4e4c410befebb4f

test:
  secret_key_base: 206ad3ddf3c698a42a553f13b9ce6efd8e1af8d5e8fe2528583b4ad21c49858351c005893517848da796c4e13f8e9f9b1615fad66b5a865a464fecd0f946a83f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
